# Generated by Django 5.2.17 on 2026-09-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0023_rentalbooking_collected_at_rentalbooking_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, default='Supplement', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
